#!/usr/bin/env bash

#============================================================
#
#         FileName: configure.sh
#
#      Descriptions:
#
#          Version: 1.0
#          Created: 2013-04-22 10:24:58
#         Revision: (none)
#
#           Author: xutao(Tony Xu), hhktony@gmail.com
#          Company: myself
#
#============================================================

[ $UID -ne 0 ] && echo "This program has to be run as root!" && exit 1

ARCH=$(uname -m)
BACKUP_DATE=`date +%F-%H%M%S`
FTP_NAME="ftp"
FTP_CONF_DIR="/etc/vsftpd"
FTP_ROOT_DIR="/var/$FTP_NAME"
FTP_VUSERNAME="ftpvuser"
FTP_VCONF_DIR="/etc/vsftpd/vusers_conf"
FTP_VROOT_DIR="/var/$FTP_VUSERNAME"
FTP_VDB_FILE="$FTP_CONF_DIR/vusers.db"
PAM_CONF_DIR="/etc/pam.d"

[ ! -d $FTP_CONF_DIR ] && mkdir -p $FTP_CONF_DIR

msg() {
  printf '%b\n' "$1" >&2
}

tips()  { echo -e " \033[1;33m$@\033[0m";  		}
die()   { echo -e " \033[1;31m✖\033[0m  $@";  exit 1; }

success()
{
  [ "$ret" -eq '0' ] && msg "\33[32m[✔]\33[0m ${1}${2}"
}

help_info()
{
  cat << EOF
  usage: $0 [OPTIONS]

  help                                  Show this message
  init                                  Init config
  user-add <username> <passwd> <rw|r>   Add user
  user-list                             List user
  gat-pass                              get user password
  user-delete <username>                Delete user
EOF
}

detect_os()
{
  if [[ -x $(command -v lsb_release 2>/dev/null) ]]; then
    DISTRO=`lsb_release -si`
    return 0
  fi

  if [ -f /etc/centos-release ]; then
    DISTRO="CentOS"
  elif [ -f /etc/debian_version ]; then
    DISTRO="Debian"
  else
    die "Unable to determine DISTRO, can not continue."
  fi
}

ensure_security()
{
  chown 600 $FTP_VDB_FILE
}

user_add()
{
  local username=$1
  local passwd=$2
  local mode=$3

  [[ -z $username || -z $passwd || -z $mode ]] &&
    die "user_add: username or passwd or mode is null!"

  [[ $mode == "rw" ]] &&
    cp $FTP_VCONF_DIR/Templates/vuser_conf.r_w $FTP_VCONF_DIR/$username ||
    cp $FTP_VCONF_DIR/Templates/vuser_conf.r   $FTP_VCONF_DIR/$unameser
  sed -i "s/vuser_name/${username}/" $FTP_VCONF_DIR/$username
  mkdir -p $FTP_VROOT_DIR/$username
  chown -R $FTP_VUSERNAME:$FTP_VUSERNAME $FTP_VROOT_DIR

  echo -e "$username\n$passwd" | $DB_LOAD -T -t hash $FTP_VDB_FILE
  ensure_security
}

user_list()
{
  [ -f $FTP_VDB_FILE ] || exit 0
  $DB_DUMP -p $FTP_VDB_FILE |
  sed -e '1,/HEADER=END/d' -e '/DATA=END/,$d' |
  sed 's/^[ \t]*//' | sed -n 'p;n'
}

get_pass()
{
  local username=$1

  [[ -z $username ]] && die "get-pass: username is null!"

  [ -f $FTP_VDB_FILE ] || exit 0
  $DB_DUMP -p $FTP_VDB_FILE |
  sed -e '1,/HEADER=END/d' -e '/DATA=END/,$d' |
  sed 's/^[ \t]*//' | grep "^${username}$" -A1 | sed -n '2p'
}

user_delete()
{
  local username=$1

  [[ -z $username ]] && die "user-delete: username is null!"

  $DB_DUMP -p $FTP_VDB_FILE |
  sed -e '1,/HEADER=END/d' -e '/DATA=END/,$d' |
  sed 's/^[ \t]*//' |
  sed "/^$username$/{n;d}" |
  sed "/^$username$/d" |
  $DB_LOAD -T -t hash ${FTP_VDB_FILE}.new

  mv ${FTP_VDB_FILE}.new $FTP_VDB_FILE
  ensure_security

  rm -rf $FTP_VCONF_DIR/$username
  mv $FTP_VROOT_DIR/$username{,-$BACKUP_DATE}
  ret="$?"
  success "$username already deleled"
  success "backed up to $FTP_VROOT_DIR/$username-$BACKUP_DATE."
}

init()
{
  cp -r $FTP_CONF_DIR{,-$BACKUP_DATE.bak}
  rm -rf $FTP_CONF_DIR/*

  for i in `ls`
  do
    cp $i $FTP_CONF_DIR -r
  done
  # rm $FTP_CONF_DIR/`basename $0` $FTP_CONF_DIR/README.md

  if [[ "$DISTRO" =~ (Ubuntu) || "$DISTRO" =~ (Debian) ]]; then
    mv $FTP_CONF_DIR/vsftpd.conf /etc
    sed -i 's:%LIB%:lib/x86_64-linux-gnu:' pam_vsftpd_vusers
  elif [[ "$DISTRO" =~ (CentOS) ]]; then
    [[ $ARCH = 'x86_64' ]] &&
      sed -i 's:%LIB%:lib64:' pam_vsftpd_vusers ||
      sed -i 's:%LIB%:lib:' pam_vsftpd_vusers
  else
    die "Unable to determine plaform, can not continue."
  fi
  mv $FTP_CONF_DIR/pam_vsftpd_vusers $PAM_CONF_DIR

  touch /var/log/vsftpd.log > /dev/null 2>&1

  useradd $FTP_NAME -d $FTP_ROOT_DIR -s /sbin/nologin > /dev/null 2>&1
  useradd $FTP_VUSERNAME -d $FTP_VROOT_DIR -s /sbin/nologin > /dev/null 2>&1

  tips "
  1. Configuration file located in /etc/vsftpd/
  2. pam_vsftpd file located in /etc/pam.d/pam_vsftpd_vusers
  3. vuser dir in /var/ftpvuser/"
}

check_db_utils()
{
  if [ -x /usr/bin/db_load ]; then
    DB_LOAD=/usr/bin/db_load
    DB_DUMP=/usr/bin/db_dump
    return 0
  fi
  die "Could not find db_load/db_dump! Please install the libdb-utils package."
}

check_db_utils

case $1 in
  --help|help|-h )
    help_info
    exit 0
    ;;
  init )
    init;;
  user-add )
    user_add $2 $3 $4;;
  user-list )
    user_list;;
  get-pass )
    get_pass $2;;
  user-delete )
    user_delete $2;;
  *)
    echo "unknown option: $1"
    help_info
    exit 1
    ;;
esac
